
spring:
    main:
        allow-bean-definition-overriding: true
    application:
        name: rootapp
    data:
        mongodb:
            uri: mongodb://root:root@223.130.153.131:27017/rootdb?retryWrites=true&w=majority
    sql:
        init:
            mode: always
            encoding: UTF-8
logging:
    level:
        org:
            hibernate:
                SQL: debug
                type: trace

jwt:
    secret: bitcamp
    expiration: 86400000
